Use better permission denied message
Several of these installers need to be updated to the more recent ones.

diff --git a/source/apt-history/apt-history-installer b/source/apt-history/apt-history-installer
--- a/source/apt-history/apt-history-installer
+++ b/source/apt-history/apt-history-installer
@@ -3,7 +3,7 @@
 #------------------------------------------------------------------------------
 # Project Name      - PerlProjects/source/apt-history/apt-history-installer
 # Started On        - Thu 12 Mar 14:54:26 GMT 2020
-# Last Change       - Sun  9 Jan 18:08:25 GMT 2022
+# Last Change       - Tue 20 Jun 20:35:23 BST 2023
 # Author E-Mail     - terminalforlife@yahoo.com
 # Author GitHub     - https://github.com/terminalforlife
 #------------------------------------------------------------------------------
@@ -32,7 +32,7 @@
 #------------------------------------------------------------------------------
 
 Err(){
-	printf 'ERROR: %s\n' "$2" 1>&2
+	printf 'Err: %s\n' "$2" 1>&2
 	[ $1 -gt 0 ] && exit $1
 }
 
@@ -41,12 +41,12 @@ if command -v curl 1> /dev/null 2>&1; then
 elif command -v wget 1> /dev/null 2>&1; then
 	DLCMD='wget -qO'
 else
-	printf "ERROR: Neither 'wget' nor 'curl' are available.\n" 1>&2
+	printf "Err: Neither 'wget' nor 'curl' are available.\n" 1>&2
 	exit 1
 fi
 
 if [ `id -u` -ne 0 ]; then
-	printf "ERROR: Root access is required for system-wide changes.\n" 1>&2
+	printf "Err: Permission denied -- are you 'root'?\n" 1>&2
 	exit 1
 fi
 
@@ -123,7 +123,7 @@ for File in 'completions' 'apt-history' 'APTHistory.pm' 'apt-history.1.gz'; do
 done
 
 if [ $ErrCount -gt 0 ]; then
-	printf 'ERROR: Failed to download one or more files.\n' 1>&2
+	printf 'Err: Failed to download one or more files.\n' 1>&2
 	exit 1
 fi
 
diff --git a/source/previewer/previewer-installer b/source/previewer/previewer-installer
--- a/source/previewer/previewer-installer
+++ b/source/previewer/previewer-installer
@@ -3,7 +3,7 @@
 #------------------------------------------------------------------------------
 # Project Name      - PerlProjects/source/previewer/previewer-installer
 # Started On        - Fri 19 Feb 01:08:09 GMT 2021
-# Last Change       - Sun  9 Jan 18:08:59 GMT 2022
+# Last Change       - Tue 20 Jun 20:38:53 BST 2023
 # Author E-Mail     - terminalforlife@yahoo.com
 # Author GitHub     - https://github.com/terminalforlife
 #------------------------------------------------------------------------------
@@ -32,7 +32,7 @@
 #------------------------------------------------------------------------------
 
 Err(){
-	printf 'ERROR: %s\n' "$2" 1>&2
+	printf 'Err: %s\n' "$2" 1>&2
 	[ $1 -gt 0 ] && exit $1
 }
 
@@ -41,12 +41,12 @@ if command -v curl 1> /dev/null 2>&1; then
 elif command -v wget 1> /dev/null 2>&1; then
 	DLCMD='wget -qO'
 else
-	printf "ERROR: Neither 'wget' nor 'curl' are available.\n" 1>&2
+	printf "Err: Neither 'wget' nor 'curl' are available.\n" 1>&2
 	exit 1
 fi
 
 if [ `id -u` -ne 0 ]; then
-	printf "ERROR: Root access is required for system-wide changes.\n" 1>&2
+	printf "Err: Permission denied -- are you 'root'?\n" 1>&2
 	exit 1
 fi
 
@@ -123,7 +123,7 @@ for File in 'completions' 'previewer' 'previewer.1.gz'; do
 done
 
 if [ $ErrCount -gt 0 ]; then
-	printf 'ERROR: Failed to download one or more files.\n' 1>&2
+	printf 'Err: Failed to download one or more files.\n' 1>&2
 	exit 1
 fi
 
