Add file-replacement prompt to installers

diff --git a/source/ubuchk/ubuchk-installer b/source/ubuchk/ubuchk-installer
--- a/source/ubuchk/ubuchk-installer
+++ b/source/ubuchk/ubuchk-installer
@@ -3,7 +3,7 @@
 #------------------------------------------------------------------------------
 # Project Name      - PerlProjects/source/ubuchk/ubuchk-installer
 # Started On        - Thu 12 Mar 14:54:26 GMT 2020
-# Last Change       - Fri  9 Jul 11:25:40 BST 2021
+# Last Change       - Wed  1 Sep 10:28:19 BST 2021
 # Author E-Mail     - terminalforlife@yahoo.com
 # Author GitHub     - https://github.com/terminalforlife
 #------------------------------------------------------------------------------
@@ -50,18 +50,23 @@ if [ `id -u` -ne 0 ]; then
 	exit 1
 fi
 
-printf 'Install latest version of UbuChk? [Y/N] '
-read Answer
-case $Answer in
-	[Yy]|[Yy][Ee][Ss])
-		printf 'Continuing with installation.\n' ;;
-	[Nn]|[Nn][Oo])
-		printf 'Abandoning installation.\n'
-		exit 0 ;;
-	*)
-		printf 'ERROR: Invalid response -- quitting.\n' 1>&2
-		exit 2 ;;
-esac
+while :; do
+	printf 'Install latest version of UbuChk? [Y/N] '
+
+	read Input
+	case $Input in
+		[Yy]|[Yy][Ee][Ss])
+			printf 'Continuing with installation.\n'
+			break ;;
+		[Nn]|[Nn][Oo])
+			printf 'Abandoning installation.\n'
+			exit 0 ;;
+		'')
+			Err 0 'Empty response -- try again.' ;;
+		*)
+			Err 0 'Invalid response -- try again.' ;;
+	esac
+done
 
 LogFile='/tmp/ubuchk-installer.log'
 [ -f "$LogFile" ] || 1> "$LogFile"
@@ -172,6 +177,29 @@ for File in\
 	'ubuchk.8.gz:/usr/share/man/man8/ubuchk.8.gz'\
 	'ubuchk:/usr/bin/ubuchk'
 do
+	Replace='False'
+
+	while :; do
+		printf "File '%s' found.\n" "${File#*:}"
+		printf 'Replace existing file? [Y/N] '
+
+		read Input
+		case $Input in
+			[Yy]|[Yy][Ee][Ss])
+				Replace='True'
+				break ;;
+			[Nn]|[Nn][Oo])
+				Replace='False'
+				break ;;
+			'')
+				Err 0 'Empty response -- try again.' ;;
+			*)
+				Err 0 'Invalid response -- try again.' ;;
+		esac
+	done
+
+	[ "$Replace" = 'True' ] || continue
+
 	printf "* Installing '%s' ... " "${File%%:*}"
 	if mv "$TmpDir/${File%%:*}" "${File#*:}" 2>> "$LogFile"; then
 		printf '\033[32m[OK]\033[0m\n'
@@ -248,7 +276,7 @@ for File in '/usr/bin/ubuchk' '/usr/bin/ubuchk-db'; do
 					case $Line in
 						'#   '[!\ ]*)
 							printf '\033[1;93m%s\e[0m\n' "${Line#\#   }" ;;
-						*|'')
+						*)
 							DepErr=$((DepErr + 1)) ;;
 					esac ;;
 			esac
