Have ubuchk-db use correct Cito args & add file
The added file is the new 'database-rk' recently added to UbuChk.

diff --git a/source/ubuchk/ubuchk-db b/source/ubuchk/ubuchk-db
--- a/source/ubuchk/ubuchk-db
+++ b/source/ubuchk/ubuchk-db
@@ -3,7 +3,7 @@
 #------------------------------------------------------------------------------
 # Project Name      - PerlProjects/source/ubuchk/ubuchk-db
 # Started On        - Mon  2 Mar 15:21:20 GMT 2020
-# Last Change       - Sun  8 Mar 17:16:44 GMT 2020
+# Last Change       - Fri 16 Oct 02:41:39 BST 2020
 # Author E-Mail     - terminalforlife@yahoo.com
 # Author GitHub     - https://github.com/terminalforlife
 #------------------------------------------------------------------------------
@@ -25,7 +25,7 @@ set -e
 . /usr/lib/tflbp-sh/YNInput
 set +e
 
-CurVer='2020-03-08'
+CurVer='2020-10-16'
 Progrm=${0##*/}
 
 while [ "$1" ]; do
@@ -45,8 +45,9 @@ ChkDep id
 
 [ `id -u` -eq 0 ] || Err 1 'Root access is required.'
 
-if YNInput 'Update UbuChk alert database?'; then
-	GHUser='terminalforlife'
+GHUser='terminalforlife'
+
+if YNInput "Update UbuChk's alert database?"; then
 	if ! command -v cito 1> /dev/null 2>&1; then
 		DBPath="/usr/share/${Progrm%-*}/database"
 		URL="https://raw.githubusercontent.com/$GHUser"
@@ -67,8 +68,35 @@ if YNInput 'Update UbuChk alert database?'; then
 		fi
 	else
 		printf "Cito found; handing '$Progrm' to it instead.\n"
-		cito -c -r "$GHUser" PerlProjects master source/ubuchk/database
+		cito -r "$GHUser" PerlProjects master source/ubuchk/database
 	fi
 else
-	printf 'Database update declined -- exiting.\n'
+	printf 'Database update declined -- skipping.\n'
+fi
+
+if YNInput "Update UbuChk's rootkit database?"; then
+	if ! command -v cito 1> /dev/null 2>&1; then
+		DBPath="/usr/share/${Progrm%-*}/database-rk"
+		URL="https://raw.githubusercontent.com/$GHUser"
+
+		if command -v wget 1> /dev/null 2>&1; then
+			DLoader="wget -qO $DBPath"
+		elif command -v curl 1> /dev/null 2>&1; then
+			DLoader="curl -so $DBPath"
+		else
+			Err 1 "Neither 'curl' nor 'wget' were found."
+		fi
+
+		FullURL="$URL/PerlProjects/master/source/ubuchk/database-rk"
+		if $DLoader "$FullURL"; then
+			printf 'Database successfully updated.\n'
+		else
+			Err 1 "File '${FullURL##*/}' failed to download via ${DLoader%% *}(1)."
+		fi
+	else
+		printf "Cito found; handing '$Progrm' to it instead.\n"
+		cito -r "$GHUser" PerlProjects master source/ubuchk/database-rk
+	fi
+else
+	printf 'Database update declined -- skipping.\n'
 fi
