Add dep checking to WCDL installer (borked?)

diff --git a/source/wcdl/wcdl-installer b/source/wcdl/wcdl-installer
--- a/source/wcdl/wcdl-installer
+++ b/source/wcdl/wcdl-installer
@@ -3,7 +3,7 @@
 #------------------------------------------------------------------------------
 # Project Name      - PerlProjects/source/wcdl/wcdl-installer
 # Started On        - Thu 12 Mar 14:54:26 GMT 2020
-# Last Change       - Wed 17 Feb 02:02:16 GMT 2021
+# Last Change       - Tue  2 Mar 17:01:10 GMT 2021
 # Author E-Mail     - terminalforlife@yahoo.com
 # Author GitHub     - https://github.com/terminalforlife
 #------------------------------------------------------------------------------
@@ -30,6 +30,11 @@
 #   coreutils (>= 8.25-2)
 #   curl (>= 7.47.0-1) | wget (>= 1.17.1-1)
 #------------------------------------------------------------------------------
+
+Err(){
+	printf 'ERROR: %s\n' "$2" 1>&2
+	[ $1 -gt 0 ] && exit $1
+}
 
 if command -v curl 1> /dev/null 2>&1; then
 	DLCMD='curl -so'
@@ -163,3 +168,50 @@ if wcdl -v > /dev/null 2>&1; then
 else
 	printf '\033[31m[ERR]\033[0m\n'
 fi
+
+printf 'Checking for dependencies:\n'
+
+for File in '/usr/bin/wcdl'; do
+	printf "* Looking in '%s' file...\n" "$File"
+
+	FileErr=0
+	if ! [ -f "$File" ]; then
+		Err 0 "File '$File' missing."
+		FileErr=$((FileErr + 1))
+	elif ! [ -r "$File" ]; then
+		Err 0 "File '$File' unreadable."
+		FileErr=$((FileErr + 1))
+	fi
+
+	if [ $FileErr -ne 0 ]; then
+		Err 0 'Unable to determine dependencies.'
+		continue
+	fi
+
+	DepErr=0
+	Found='False'
+	while read Line; do
+		if [ "$Line" = '#' ]; then
+			continue
+		elif [ "$Line" = '# Dependencies:' ]; then
+			Found='True'
+		elif [ "$Found" = 'True' ]; then
+			# Line to help debug parsing on stubborn files.
+			#printf '\e[2;37m%s\e[0m\n' "$Line"
+
+			case $Line in
+				'#'------*)
+					break ;;
+				*)
+					case $Line in
+						'#   '[!\ ]*)
+							printf '\033[1;93m%s\e[0m\n' "${Line#\#   }" ;;
+						*|'')
+							DepErr=$((DepErr + 1)) ;;
+					esac ;;
+			esac
+		fi
+	done < "$File"
+
+	[ $DepErr -eq 0 ] || Err 0 'One or more invalid dependencies detected.'
+done
